### ISSUE TITLE
Freebayes bed index issue

### ISSUE THREAD

**Issue by kristyhoran** [jodyphelan/pathogen-profiler#12]
Hi @jodyphelan !! Many thanks for putting together this awesome tool. I am looking to implement it for identification of resistance for TB from WGS for public health reporting. During the validation process, using freebayes as the caller, I have noticed that all of my sequences are being called Lineage 4.9 (H37Rv-like), however, previous versions have called the same sequences as various other lineages. Furthermore, when I use bcftools as the caller this does not occur (I do see some 4.9, but other lineages as well in my dataset, which were consistent for the most part with older versions).

Upon investigating this, I noted that no barcode SNPs were being identified in the vcf file output by TB-profiler (and therefore pathogen-profiler), even when they were present in the bam file when using freebayes as the caller. I use freebayes routinely for other purposes and found this very odd. I think it has to do with the `get_bed_gt` function in the bam class of pathogen-profiler, the bed file used is 1-base (which is why bcftools works), but I think that freebayes is uses 0-base, which means there is likely an offset of 1 error happening - when calling barcode SNPs.

Do you observe the same behaviour?

Many thanks again

Cheers
Kristy

**Comment by jodyphelan** [comment]
Hey @kristyhoran ,

Thanks for reporting and investigating the issue! I'll take a look but I think you might be right in the 0- vs 1-base bed issue.

**Comment by kristyhoran** [comment]
@jodyphelan Thanks for quick response! 
it was all of the samples (>4000 ) in my validation set. The dataset includes sequences from diverse public sources and internal sequencing. 

I am using TB-profiler 4.2.0 and pathogen-profiler both installed from GitHub using `pip` (on 29th April) into a conda environment with: 
Freebayes v1.3.2-dirty. 
samtools 1.10
bwa 0.7.17-r1188
bcftools 1.10.2

I might also try a completely fresh install and see if I can reproduce my mistakes.. there may be some aberrant dependency kicking about in my environment that is causing the unexpected behaviour. I will let you know what happens.

**Comment by jodyphelan** [comment]
Seems to work alright with those versions for me. Ok, let me know if you find anything.  Also worth mentioning that the output from freebayes is read straight into tb-profiler without storing it in a vcf (https://github.com/jodyphelan/pathogen-profiler/blob/master/pathogenprofiler/bam.py#L141-L149). If you wanna test out the freeabyes part you can run something like:

```
samtools view -Mb -L /home/jody/miniconda3/envs/test/share/tbprofiler//tbdb.barcode.bed ../bam/por5A.bam -T /home/jody/miniconda3/envs/test/share/tbprofiler//tbdb.fasta > tmp.bam

freebayes -f /home/jody/miniconda3/envs/test/share/tbprofiler//tbdb.fasta -t /home/jody/miniconda3/envs/test/share/tbprofiler//tbdb.barcode.bed tmp.bam --haplotype-length -1 | bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT\t%AD]\n'
```

**Comment by kristyhoran** [comment]
Hi @jodyphelan I have update my environment (freebayes 1.3.5) and this seems to have solved my issue...
