### ISSUE TITLE
Issue with --match-ref function resultant barcode file

### ISSUE THREAD

**Issue by thomcuddihy** [jodyphelan/pathogen-profiler#14]
Needed to change reference to NC_000962.3 from TBDB default Chromosome. Other files were corrected fine, but barcode remained the same. On inspection, it appears that the shutil.copyfile call for the extra_files that occurs after the chromosome conversion reverts it to the original condition.

This wouldn't be issue if a correct bed file is supplied with `--barcode` to create_db command, but using the documented update_tbdb command presents the default TBDB barcode file siliently. Have proposed solution in #13 just by re-ordering the code. Thanks

**Comment by jodyphelan** [comment]
Hi @thomcuddihy 

Thanks for taking the time to debug and put in a PR, much appreciated!
I've merged it now and will put out a new release soon.
