### ISSUE TITLE
snpEff ann tries to write to read-only directory

### ISSUE THREAD

**Issue by pvanheus** [jodyphelan/pathogen-profiler#5]
Hi there

I've been trying to update the Galaxy wrapper of tb-profiler and hitting a bug. So a bit of background - the Galaxy tools-iuc CI runs tools like tb-profiler from (Docker) containers. This fails in my current PR, and the reason is [this line](https://github.com/jodyphelan/pathogen-profiler/blob/master/pathogenprofiler/vcf.py#L61). `snpEff ann` downloads the snpEff database on the fly and, on the Docker container built from the bioconda recipe, tries to put it in `/usr/local/share/snpeff-5.0-1/data`. When using the Docker container as a non-root user (as Galaxy uses it), this location is not writeable.

A solution might be to use the `-dataDir` option of `snpEff` to specify a writeable location. The downside of this is downloading the database each time the tool is run.

**Comment by pvanheus** [comment]
One alternative I am exploring is to pre-download the snpEff database in the bioconda build. This will mean that the biocontainers Docker image has the snpEff already present, so it would not be re-downloaded. A PR to bioconda implementing that change is [here](https://github.com/bioconda/bioconda-recipes/pull/33737).

**Comment by pvanheus** [comment]
Following on from my previous comment - the bioconda [pr](https://github.com/bioconda/bioconda-recipes/pull/33737) fixes the problem described above and this [PR](https://github.com/jodyphelan/pathogen-profiler/pull/6) provides a more elegant solution to avoid the crash I encountered.

**Comment by jodyphelan** [comment]
Thanks @pvanheus, much appreciated!
